### ISSUE TITLE
Does not correctly get bools

### ISSUE THREAD

**Issue by KammererTob** [arve0/vue-persistent-state#1]
The library does not correctly get falsey or false values stored in the store. This is caused by this line:

`let val = store.get(key) || initialState[key]`

As soon as the stored value is falsey it falls back to the initial value.
My suggestion would be to replace this line with:

`let val = store.get(key, initialState[key])`

See https://github.com/marcuswestin/store.js/blob/master/src/store-engine.js#L21

**Comment by arve0** [comment]
Thank you for reporting, and also for the fix. This has been fixed in `v0.1.1`.
