### ISSUE TITLE
watchers get triggered multiple times  

### ISSUE THREAD

**Issue by Gormartsen** [arve0/vue-persistent-state#4]
Global mixin with watchers will add watchers to each component.
As a result any changes to `this.$store.myvalue` will trigger multiple (equal to the count of components) store.item.

I suggest to use `this.$watch(name, function)` on `created` with a global trigger if watchers has been added (usually to first component?)

**Comment by arve0** [comment]
Thanks for reporting, and sorry for the late reply. I'll see if I find some time looking into this.

**Comment by arve0** [comment]
Fixed in `v0.2.0`.
